ALTER TABLE records 
ADD COLUMN IF NOT EXISTS period_covered VARCHAR(255),
ADD COLUMN IF NOT EXISTS volume VARCHAR(100),
ADD COLUMN IF NOT EXISTS duplication VARCHAR(100),
ADD COLUMN IF NOT EXISTS time_value VARCHAR(50),
ADD COLUMN IF NOT EXISTS utility_value VARCHAR(50);
